theme: jekyll-theme-minimal

title: [ . ]
description: [ The room a dying poet took
at nightfall in a dead hotel
had both directories -- the Book
of Heaven and the Book of Bell.

Not tears, not terror, but a blend
of anonymity and doom,
it seemed, that room, to condescend
to imitate a normal room.

Soon afterwards the room was mine.
A similar striped cageling, I
groped for the lamp and found the line
"Alone, unknown, unloved, I die"

]
